# Generated by Django 4.2.5 on 2023-09-26 10:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('id_user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31)),
            ],
        ),
    ]
