# Generated by Django 4.2.5 on 2023-09-28 10:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatieTicketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
