# Generated by Django 4.2.5 on 2023-10-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatieTicketing', '0004_ticket_tickettype'),
        ('aplicatieTicketing', '0006_ticket_user'),
    ]

    operations = [
    ]
